# Generated by Django 4.2.6 on 2023-10-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quizzes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField(verbose_name='ID вопроса')),
                ('question_text', models.CharField(max_length=150, unique=True, verbose_name='Текст вопроса')),
                ('answer_text', models.CharField(max_length=150, verbose_name='Ответ на вопрос')),
                ('date', models.DateTimeField(verbose_name='Дата создания вопроса')),
            ],
        ),
    ]
