# Generated by Django 4.2.6 on 2023-10-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzes',
            name='count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='question_id',
            field=models.IntegerField(unique=True, verbose_name='ID вопроса'),
        ),
    ]
