# Generated by Django 4.2.6 on 2023-10-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quizzes_count_alter_quizzes_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzes',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
